<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <LangVersion>latest</LangVersion>
    <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
    <AssemblyName>TShockEconomyExp</AssemblyName>
    <RootNamespace>TShockEconomyExp</RootNamespace>
    <DefaultItemExcludes>$(DefaultItemExcludes);NamulRpgConfigTool\**</DefaultItemExcludes>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Data.Sqlite" Version="9.0.0" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="ModFramework">
      <HintPath>lib\ModFramework.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="OTAPI">
      <HintPath>lib\OTAPI.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="TerrariaServer">
      <HintPath>lib\TerrariaServer.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="TShockAPI">
      <HintPath>lib\TShockAPI.dll</HintPath>
      <Private>False</Private>
    </Reference>
  </ItemGroup>

</Project>
